# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IntervalContains <- function(x, inf, sup, min, max, bound, class_str) {
    .Call(`_set6_IntervalContains`, x, inf, sup, min, max, bound, class_str)
}

IntervalContainsAll <- function(x, inf, sup, min, max, bound, class_str) {
    .Call(`_set6_IntervalContainsAll`, x, inf, sup, min, max, bound, class_str)
}

PrimesContains <- function(x) {
    .Call(`_set6_PrimesContains`, x)
}

